baseURL = "http://finwhizz.in"
languageCode = "en-us"
title = "FinWhizz Consultancy"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id="UA-203714790-1"


  [params.homepage_meta_tags]
    meta_description = "FinWhizz - One Stop Solution for all your Compliance"
    meta_og_title = "FinWhizz Consultancy"
    meta_og_type = "website"
    meta_og_url = "https://finwhizz.in"
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = ""
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2


[[menu.main]]
    name = "Fin Entrepreneurs"
    url = "/work/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
