baseURL = "https://vikaskakolu.github.io/"
languageCode = "en-us"
title = "FinWhizz Consultancy"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "FinWhizz - One Stop Solution for all your Compliance"
    meta_og_title = "FinWhizz Consultancy"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2


[[menu.main]]
    name = "Fin Entrepreneurs"
    url = "/work/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
